enabled: true
disable-rak: false
synapses:
- enabled: true
  server-ip: play.turbinepe.tk
  server-port: 19132
  is-main-server: true
  server-password: 32bitlongkey
  description: "Hub"
  verbose-logging: false
- enabled: true
  server-ip: play.turbinepe.tk
  server-port: 19133
  is-main-server: false
  server-password: 32bitlongkey
  description: "Realistic"
  verbose-logging: false
- enabled: true
  server-ip: play.turbinepe.tk
  server-port: 19134
  is-main-server: false
  server-password: 32bitlongkey
  description: "Creative"
  verbose-logging: false
- enabled: true
  server-ip: play.turbinepe.tk
  server-port: 19135
  is-main-server: false
  server-password: 32bitlongkey
  description: "EF"
  verbose-logging: false
loadingScreen: false
